ALTER TABLE urls ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE;
ALTER TABLE urls ADD COLUMN IF NOT EXISTS allowed_ips TEXT;
ALTER TABLE urls ADD COLUMN IF NOT EXISTS splash_page BOOLEAN DEFAULT FALSE;
ALTER TABLE urls ADD COLUMN IF NOT EXISTS sensitive_warning BOOLEAN DEFAULT FALSE;
