ALTER TABLE clicks ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS region VARCHAR(100);
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS os VARCHAR(100);
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS device_type VARCHAR(50);
-- Browser and Country already exist
